### ISSUE TITLE
Wrong seg image with PIL

### ISSUE THREAD

**Issue by phy25** [BUGenerator/Web#13]
Trying to color map the grayscale image to a colorful one, but it doesn't work currently.

**Comment by phy25** [comment]
```
[Thu Nov 15 00:36:42.519733 2018] [:error] [pid 16046] [remote 172.31.10.155:27642] Traceback (most recent call last):
[Thu Nov 15 00:36:42.519737 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Thu Nov 15 00:36:42.519740 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     response = self.full_dispatch_request()
[Thu Nov 15 00:36:42.519743 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Thu Nov 15 00:36:42.519746 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     rv = self.handle_user_exception(e)
[Thu Nov 15 00:36:42.519748 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
[Thu Nov 15 00:36:42.519751 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     reraise(exc_type, exc_value, tb)
[Thu Nov 15 00:36:42.519753 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Thu Nov 15 00:36:42.519756 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     raise value
[Thu Nov 15 00:36:42.519758 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Thu Nov 15 00:36:42.519761 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     rv = self.dispatch_request()
[Thu Nov 15 00:36:42.519764 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[Thu Nov 15 00:36:42.519766 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Nov 15 00:36:42.519769 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/current/app/upload.py", line 47, in post_upload
[Thu Nov 15 00:36:42.519781 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     predict.save_by_path(seg, temp_path)
[Thu Nov 15 00:36:42.519783 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/current/app/predict.py", line 53, in save_by_path
[Thu Nov 15 00:36:42.519786 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     return Image.fromarray(seg, mode='RGB').save(path)
[Thu Nov 15 00:36:42.519788 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/PIL/Image.py", line 2511, in fromarray
[Thu Nov 15 00:36:42.519790 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
[Thu Nov 15 00:36:42.519792 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/PIL/Image.py", line 2454, in frombuffer
[Thu Nov 15 00:36:42.519795 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     return frombytes(mode, size, data, decoder_name, args)
[Thu Nov 15 00:36:42.519797 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/PIL/Image.py", line 2387, in frombytes
[Thu Nov 15 00:36:42.519799 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     im.frombytes(data, decoder_name, args)
[Thu Nov 15 00:36:42.519802 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/PIL/Image.py", line 801, in frombytes
[Thu Nov 15 00:36:42.519804 2018] [:error] [pid 16046] [remote 172.31.10.155:27642]     raise ValueError("not enough image data")
[Thu Nov 15 00:36:42.519807 2018] [:error] [pid 16046] [remote 172.31.10.155:27642] ValueError: not enough image data
```

**Comment by phy25** [comment]
Dropped color support because it might be too slow :-(. Reverting to see whether the B/W image works.
